service: auth-server
provider:
  name: aws
  runtime: nodejs20.x
  region: eu-central-1
  timeout: 30
  environment:
    CLIENT_ID: ${file(config.json):CLIENT_ID}
    CLIENT_SECRET: ${file(config.json):CLIENT_SECRET}
    CALENDAR_ID: ${file(config.json):CALENDAR_ID}
functions:
  getAuthURL:
    handler: handler.getAuthURL
    layers:
      - arn:aws:lambda:eu-central-1:590183738570:layer:googleapis-layer:1
    events:
      - httpApi:
          path: /api/get-auth-url
          method: get
          cors: true
  getAccessToken:
    handler: handler.getAccessToken
    timeout: 30
    layers:
      - arn:aws:lambda:eu-central-1:590183738570:layer:googleapis-layer:1
    events:
      - httpApi:
          path: /api/token/{code}
          method: get
          cors: true
  getCalendarEvents:
    handler: handler.getCalendarEvents
    layers:
      - arn:aws:lambda:eu-central-1:590183738570:layer:googleapis-layer:1
    events:
      - httpApi:
          path: /api/get-events/{access_token}
          method: get
          cors: true
plugins:
  - serverless-webpack
  - serverless-apigateway-service-proxy
